### ISSUE TITLE
(Idea) Save intermediate images at specific percentages

### ISSUE THREAD

**Issue by Letiliel** [lowfuel/progrockdiffusion#44] opened 2022-06-02 18:22 UTC
I'd like to save renders at 70%, 80% and 90% progress, all the time. It's currently possible by giving an array with specific steps to the intermediate_saves setting, but it's a pain to recalculate the corresponding steps whenever I change the total steps.
The idea would be for example to provide an array with percentages as decimals, in my case [0.7, 0.8, 0.9] and have PRD calculate the corresponding steps to save.

**Comment by lowfuel** [comment] 2022-06-02 20:45
I love that. Always frustrating when things have to be updated just because some other value was updated.

I've checked it on so that you can have either method:

[.5, .7, .9] will save at 50%, %70, %90 of steps, but the old method (integers instead of floating point) will still save at specific steps.

A quick test seems to work, but let me know if you have any issues!

**Comment by Letiliel** [comment] 2022-06-03 12:32
Thanks! \o
It doesn't really work for me though with `intermediate_saves: [.7, .8, .9]`
Most of the time no partial is saved, sometimes I get one, and once I got the three. I haven't checked your code or noticed a pattern to the issue yet

**Comment by lowfuel** [comment] 2022-06-03 12:50
I'll dive in and figure it out.

**Comment by lowfuel** [comment] 2022-06-03 13:14
So far it's worked for me every time.

From your problem description I can't tell if you mean you're getting different results from run to run without changing any settings, or you mean some settings work and some don't.

If it's that certain settings are not working, please post the full settings from one that's failing to save so I can reproduce it. Thanks!

**Comment by Letiliel** [comment] 2022-06-03 13:20
I'm changing settings

My current ones:
`{
    batch_name: "Baroque fractal mechanical",
    text_prompts: {
        "0": [
            "A beautiful metallic dragon, baroque, character design, concept art:110",
            "An intricate fractal of leaves, artstation, concept art, CGsociety:60",
            "by Petros Afshar and Ernst Haeckel:80",
            "blue neon colors, art nouveau:60",
        ],
    },
    n_batches: 2,
    steps: 120,
    display_rate: 2,
    width_height_scale: 1,
    width: 640,
    height: 1561,
    set_seed: "random_seed",
    image_prompts: {},
    clip_guidance_scale: 100000,
    tv_scale: 0,
    range_scale: 150,
    sat_scale: 0,
    cutn_batches: 8,
    cutn_batches_final: "None",
    max_frames: 10000,
    interp_spline: "Linear",
    init_image: "./init_brown.png",
    init_scale: 1000,
    skip_steps: 0,
    skip_steps_ratio: 0.4,
    frames_scale: 1500,
    frames_skip_steps: "60%",
    perlin_init: false,
    perlin_mode: "mixed",
    skip_augs: false,
    randomize_class: true,
    clip_denoised: false,
    clamp_grad: true,
    clamp_max: 0.1,
    fuzzy_prompt: false,
    rand_mag: 0.035,
    eta: 0.75,
    diffusion_model: "512x512_diffusion_uncond_finetune_008100",
    use_secondary_model: false,
    diffusion_steps: 1000,
    sampling_mode: "ddim",
    ViTB32: true,
    ViTB16: true,
    ViTL14: true,
    ViTL14_336: false,
    RN101: false,
    RN50: true,
    RN50x4: false,
    RN50x16: false,
    RN50x64: false,
    cut_overview: "[5]*600+[1]*400",
    cut_innercut: "[1]*600+[5]*400",
    cut_ic_pow: 1,
    cut_ic_pow_final: "None",
    cut_icgray_p: "[0.2]*400+[0]*600",
    animation_mode: "None",
    key_frames: true,
    angle: "0:(0)",
    zoom: "0: (1), 10: (1.05)",
    translation_x: "0: (0)",
    translation_y: "0: (0)",
    video_init_path: "/content/training.mp4",
    extract_nth_frame: 2,
    stop_early: 0,
    fix_brightness_contrast: true,
    adjustment_interval: 5,
    high_contrast_threshold: 90,
    high_contrast_adjust_amount: 0.85,
    high_contrast_start: 20,
    high_contrast_adjust: true,
    low_contrast_threshold: 20,
    low_contrast_adjust_amount: 2,
    low_contrast_start: 20,
    low_contrast_adjust: true,
    high_brightness_threshold: 180,
    high_brightness_adjust_amount: 0.85,
    high_brightness_start: 0,
    high_brightness_adjust: true,
    low_brightness_threshold: 40,
    low_brightness_adjust_amount: 1.15,
    low_brightness_start: 0,
    low_brightness_adjust: true,
    sharpen_preset: "Off",
    keep_unsharp: false,
    gobig_orientation: "vertical",
    gobig_scale: 2,
    symmetry_loss: false,
    symm_loss_scale:  161803,
    symm_switch: 45,
    intermediate_saves: [.7, .8, .9]
}`

**Comment by lowfuel** [comment] 2022-06-03 13:32
Thanks. Trying it now. FYI I also just checked in a small fix to handle when the values weren't floating point, but that shouldn't matter for your settings above.

**Comment by lowfuel** [comment] 2022-06-03 13:37
I think it might be related to the fact that total steps changes when the fix_brightness_contrast triggers so sometimes it's not reaching the step that will save a partial. 

I've been wanting to fix that steps-changing thing anyway, it's always bugged me, so let me see if I can sort that out (it's someone else's code).

**Comment by lowfuel** [comment] 2022-06-03 15:50
Just about there. Also, as an aside, getting some amazing stuff with your settings. ;)

**Comment by Letiliel** [comment] 2022-06-03 16:00
:+1: 
The prompt is from ilconigliobianco who shared on Discord :)

**Comment by lowfuel** [comment] 2022-06-03 16:49
Well this has sent me down a bit of a rabbit hole, but thanks to the bug you found I've completely revamped the progress bar and how steps are tracked. Fixes a ton of stuff. I will check it in after a few more tests.

**Comment by lowfuel** [comment] 2022-06-03 18:25
Okay, it's checked in. This included a fairly big change to how steps are tracked and displayed, so please let me know if you spot any side effects.

**Comment by Letiliel** [comment] 2022-06-09 11:56
It's working well so far, nice improvements, thanks!

**Closed** 2022-06-09 11:56 UTC
