### ISSUE TITLE
Results turn out pink

### ISSUE THREAD

**Issue by nikocraft** [lowfuel/progrockdiffusion#68] opened 2022-06-22 20:42 UTC
Hi any idea what this could be result of?

last 3 images turned out 100% pink
![image](https://user-images.githubusercontent.com/443080/175132145-a5251cfe-1298-4b7d-ba20-009c9730e8d2.png)

console log
![image](https://user-images.githubusercontent.com/443080/175132331-32167e38-97d5-4fb4-9faa-6a7dfec9bc52.png)

partials

![image](https://user-images.githubusercontent.com/443080/175132612-abb6e95c-d6da-44c0-8ab5-55c2cff5e2d5.png)

my settings

```
{
  "batch_name": "Default",
  "text_prompts": {
    "0": ["Looking from above we see a Star Gate in the middle of a desert, by Noah Bradley, Trending on Artstation."]
  },
  "n_batches": 30,
  "steps": 220,
  "display_rate": 10,
  "width": 832,
  "height": 512,
  "set_seed": "random_seed",
  "image_prompts": {},
  "clip_guidance_scale": "auto",
  "tv_scale": -2,
  "range_scale": 150,
  "sat_scale": 0,
  "cutn_batches": 8,
  "cutn_batches_final": null,
  "init_image": null,
  "skip_steps_ratio": 0.33,
  "init_scale": 1000,
  "skip_steps": 0,
  "perlin_init": false,
  "perlin_mode": "mixed",
  "skip_augs": false,
  "randomize_class": true,
  "clip_denoised": false,
  "clamp_grad": true,
  "clamp_max": "auto",
  "fuzzy_prompt": false,
  "rand_mag": 0.05,
  "eta": "auto",
  "diffusion_model": "512x512_diffusion_uncond_finetune_008100",
  "use_secondary_model": true,
  "sampling_mode": "ddim",
  "diffusion_steps": 1000,
  "ViTB32": true,
  "ViTB16": true,
  "ViTL14": true,
  "ViTL14_336": false,
  "RN101": false,
  "RN50": false,
  "RN50x4": false,
  "RN50x16": false,
  "RN50x64": false,
  "cut_overview": "[5]*400+[1]*600",
  "cut_innercut": "[1]*400+[5]*600",
  "cut_ic_pow": 1,
  "cut_ic_pow_final": null,
  "cut_icgray_p": "[0.2]*400+[0]*600",
  "smooth_schedules": false,
  "intermediate_saves": 12,
  "stop_early": 0,
  "fix_brightness_contrast": true,
  "high_contrast_threshold": 80,
  "high_contrast_adjust_amount": 0.85,
  "high_contrast_start": 20,
  "high_contrast_adjust": true,
  "low_contrast_threshold": 20,
  "low_contrast_adjust_amount": 2,
  "low_contrast_start": 20,
  "low_contrast_adjust": true,
  "high_brightness_threshold": 180,
  "high_brightness_adjust_amount": 0.85,
  "high_brightness_start": 0,
  "high_brightness_adjust": true,
  "low_brightness_threshold": 40,
  "low_brightness_adjust_amount": 1.15,
  "low_brightness_start": 0,
  "low_brightness_adjust": true,
  "gobig_orientation": "vertical",
  "gobig_scale": 2,
  "keep_unsharp": false,
  "symmetry_loss_v": false,
  "symmetry_loss_h": false,
  "symm_loss_scale": 2400,
  "symm_switch": 45,
  "interp_spline": "Linear",
  "max_frames": 10000,
  "sharpen_preset": "Off",
  "frames_scale": 1500,
  "frames_skip_steps": "60%",
  "animation_mode": "None",
  "key_frames": true,
  "angle": "0:(0)",
  "zoom": "0: (1), 10: (1.05)",
  "translation_x": "0: (0)",
  "translation_y": "0: (0)",
  "video_init_path": "/content/training.mp4",
  "extract_nth_frame": 2
}


```

**Comment by lowfuel** [comment] 2022-06-23 00:24
You know, I've seen this come up elsewhere (and not just in PRD). I think it might have something to do with not running a number of steps that are divisible evenly by 1000. Can you try 250 or 200 instead of 220, and let me know?

**Comment by lowfuel** [comment] 2022-06-23 00:28
I'll try running it here, too, and see if I get the same result. Someone asked me about this the other day, but my batch with his prompt came out fine. The difference was I had 250 steps and he had 600. I think there might be something weird that happens in a batch situation when there's "leftover" diffusion steps.

**Comment by lowfuel** [comment] 2022-06-23 13:12
I found a possible cause for this. Testing a fix now. I believe it is related to auto_brightness_contrast, which changes a value whenever it triggers and that value is not being reset between images, so over the course of a batch it might be getting more and more out of whack. While I'm testing, you could try turning this off and see if the issue goes away?
Alternatively, you could set perlin_init to true, because that does cause this variable to get reset between images.

**Comment by lowfuel** [comment] 2022-06-23 16:55
Okay, potential fix is checked in. Let me know if you continue to see this issue. I ran your set up to image 17 out of 30 and my results were still looking good.

**Comment by nikocraft** [comment] 2022-06-23 17:30
I have not been able to replicate it and I've generated quite a lots of images in last 24 hours :)

**Comment by lowfuel** [comment] 2022-06-23 17:36
So the issue would only occur:

- after the first image in a batch
- after automatic brightness/contrast correct has triggered a few times

Essentially, auto brightness/contrast is changing a variable which is getting re-used in subsequent images in a batch. The longer the batch runs and the more times this correction triggers, the more this variable gets out of whack.

My fix is simply to make sure we reset to a baseline value when starting a new image in a batch.

This is why it was hard to track down. Some batches never need correction (or just so little that it would take tons of images to see the problem), some people don't run batches with the correction enabled, and some people don't use batches (like me). Also, if perlin_init is set to true the problem wouldn't occur because it was already set to create a new value for each image. 

Thanks for posting your settings and the example, I was able to re-create and run a second batch with the fix which looked great.

**Comment by nikocraft** [comment] 2022-06-23 17:46
Great I see the fix is already pushed :) Thanks for fixing this so quickly! :)

**Comment by lowfuel** [comment] 2022-06-24 01:22
Feel free to re-open this if the issue is still there!

**Closed by lowfuel** 2022-06-24 01:22 UTC

**Comment by KnoBuddy** [comment] 2022-07-20 21:38
I'm running into the same situation on a single batch run.

![image](https://user-images.githubusercontent.com/64171756/180086737-05a81ef4-86ee-4263-8367-9c0e627f81a3.png)

```
{ "text_prompts": {

"0": [

"A portrait of a medieval warrior girl by koral bak, artstation:1.5","playing card background:1.0", "fantasy, symmetric portrait, vray render, unreal engine, hyperrealism, photorealism, volumetric lighting:0.3"

],},
"image_prompts": {},
"display_rate": 5,
"clip_guidance_scale": 15000,
"tv_scale": 25,
"range_scale": 2500,
"sat_scale": 250,
"cutn_batches": 1,
"interp_spline": "Linear",
"init_image": null,
"init_scale": 1000,
"skip_steps": 20,
"frames_scale": 1500,
"frames_skip_steps": "60%",
"perlin_init": false,
"perlin_mode": "mixed",
"skip_augs": true,
"randomize_class": true,
"clip_denoised": false,
"clamp_grad": true,
"clamp_max": 0.1,
"seed": 12391,
"fuzzy_prompt": false,
"rand_mag": 0.05,
"eta": 0.8,
"width": 512,
"height": 704,
"diffusion_model": "portrait_generator_v001",
"use_secondary_model": false,
"steps": 200,
"diffusion_steps": 1000,
"diffusion_sampling_mode": "ddim",
"ViTB32": true,
"ViTB16": true,
"ViTL14": false,
"ViTL14_336px": false,
"RN101": false,
"RN50": true,
"RN50x4": false,
"RN50x16": false,
"RN50x64": false,
"ViTB32_laion2b_e16": false,
"ViTB32_laion400m_e31": false,
"ViTB32_laion400m_32": false,
"ViTB32quickgelu_laion400m_e31": false,
"ViTB32quickgelu_laion400m_e32": false,
"ViTB16_laion400m_e31": false,
"ViTB16_laion400m_e32": false,
"RN50_yffcc15m": false,
"RN50_cc12m": false,
"RN50_quickgelu_yfcc15m": false,
"RN50_quickgelu_cc12m": false,
"RN101_yfcc15m": false,
"RN101_quickgelu_yfcc15m": false,
"cut_overview": "[12]*400+[4]*600",
"cut_innercut": "[4]*400+[12]*600",
"cut_ic_pow": "[1]*1000",
"cut_icgray_p": "[0.2]*400+[0]*600",
"key_frames": true,
"smooth_schedules": false,
"intermediate_saves": 0,
"stop_early": 0,
"fix_brightness_contrast": true,
"high_contrast_threshold": 80,
"high_contrast_adjust_amount": 0.85,
"high_contrast_start": 20,
"high_contrast_adjust": true,
"low_contrast_threshold": 20,
"low_contrast_adjust_amount": 2,
"low_contrast_start": 20,
"low_contrast_adjust": true,
"high_brightness_threshold": 180,
"high_brightness_adjust_amount": 0.85,
"high_brightness_start": 0,
"high_brightness_adjust": true,
"low_brightness_threshold": 40,
"low_brightness_adjust_amount": 1.15,
"low_brightness_start": 0,
"low_brightness_adjust": true,
"gobig_scale": 2,
"gobig_skip_ratio": 0.6,
"keep_unsharp": false,
"symmetry_loss_v": true,
"symmetry_loss_h": false,
"symm_loss_scale":  20000,
"symm_switch": 100,
"interp_spline": "Linear",
"max_frames": 1000,
"sharpen_preset": "Off",
"frames_scale": 1500,
"frames_skip_steps": "60%",
"animation_mode": "None",
"key_frames": true,
"angle": "0:(0)",
"zoom": "0: (1), 10: (1.05)",
"translation_x": "0: (0)",
"translation_y": "0: (0)",
"video_init_path": "/content/training.mp4",
"extract_nth_frame": 2,
"use_jpg": false,
"display_rate": 1,
}
```

**Comment by KnoBuddy** [comment] 2022-07-20 21:44
Changing clip_guidance_scale to auto results in a green image.

![image](https://user-images.githubusercontent.com/64171756/180087594-cff934df-f743-4531-b97c-2197a19ac11d.png)

**Comment by lowfuel** [comment] 2022-07-20 23:02
Can you try upping clip_guidance_scale to around 30000?
I think I need to change the auto calculation for it to account for use_secondary_model being false, as that seems to have a big effect on this and a few other values (I was never able to run this way before so I didn't know).

**Comment by KnoBuddy** [comment] 2022-07-22 02:07
30000 fixed the issue completely. I was using settings from someone's DD file so it makes sense some things would need tweaking. I have never seen results like this. Thanks for the help.

**Comment by lowfuel** [comment] 2022-07-22 02:11
No problem. There is some work underway to improve how settings are handled, including the "auto" calculation, so as part of that we can adjust things based on use_secondary_model.

**Comment by KnoBuddy** [comment] 2022-07-28 18:30
Is there something going on with symmetry/clip guidance/secondary model? It's almost like turning on v symmetry flips the other settings or something. I keep getting pink results with secondary on and normal results with it off.

**Comment by lowfuel** [comment] 2022-07-28 18:38
Not that I'm aware of. I'll do some tests. Would be helpful if you could post your settings.
